# Generated by Django 5.1.3 on 2024-11-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Num_pieces',
            new_name='number_of_pieces',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('items', models.ManyToManyField(to='dashboard.item')),
            ],
        ),
    ]
