# Generated by Django 5.1.3 on 2024-12-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_depreciation_fixedoperationalcoast_workinghours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depreciation',
            old_name='Investment_cost',
            new_name='investment_cost',
        ),
        migrations.RenameField(
            model_name='fixedoperationalcoast',
            old_name='Bills',
            new_name='bills',
        ),
        migrations.RenameField(
            model_name='fixedoperationalcoast',
            old_name='Doctor_salaries',
            new_name='doctor_salaries',
        ),
        migrations.RenameField(
            model_name='fixedoperationalcoast',
            old_name='Rent',
            new_name='rent',
        ),
        migrations.RenameField(
            model_name='fixedoperationalcoast',
            old_name='Routine_markting',
            new_name='routine_marketing',
        ),
        migrations.RenameField(
            model_name='fixedoperationalcoast',
            old_name='SecretaryAndAssistant',
            new_name='secretary_and_assistant',
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specific_items', models.ManyToManyField(related_name='specialization_items', to='dashboard.item')),
                ('specific_lists', models.ManyToManyField(related_name='specialization_lists', to='dashboard.list')),
            ],
        ),
    ]
