# Generated by Django 5.1.3 on 2024-12-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_investment_cost_depreciation_investment_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixedOperationalCoast',
            new_name='FixedOperationalCost',
        ),
    ]
